restool: support new dpni_create dist_key_size parameter
Signed-off-by: Ionut-robert Aron <ionut-robert.aron@nxp.com>

diff --git a/scripts/ls-main b/scripts/ls-main
--- a/scripts/ls-main
+++ b/scripts/ls-main
@@ -691,7 +691,8 @@ The options are:
 	-o, --options=OPTIONS				Comma separated options. Supported values are:
 							DPNI_OPT_TX_FRM_RELEASE, DPNI_OPT_NO_MAC_FILTER,
 							DPNI_OPT_HAS_POLICING, DPNI_OPT_SHARED_CONGESTION,
-							DPNI_OPT_HAS_KEY_MASKING, DPNI_OPT_NO_FS, DPNI_OPT_CUSTOM_CG.
+							DPNI_OPT_HAS_KEY_MASKING, DPNI_OPT_NO_FS, DPNI_OPT_CUSTOM_CG,
+							DPNI_OPT_SHARED_HASH_KEY.
 	-nq, --num-queues=NUM_QUEUES			Number of TX/RX queues use for traffic distribution.
 							Valid range [1-16]. Default value is number of cores.
 	-t, --num-tcs=NUM_TCS				Number of traffic classes (TCs) reserved for the DPNI.
@@ -707,6 +708,8 @@ The options are:
 							Valid range [1-1024]. Default value is 64.
 	-g, --num-cgs=CONGESTION_GROUPS			Number of congestion groups (CGs), reserved for the DPNI.
 							Valid range [1-128]. Defaults to one per TC.
+	-d, --dist-key-size=KEY_SIZE			Maximum key size for the distribution.
+							Valid range [1-56]. Defaults to 56.
 	-c, --container <dprc.X>                        Specifies the parent container name. e.g. dprc.2, dprc.3 etc.
 
 <endpoint> is one of the following:
@@ -782,6 +785,14 @@ process_addni() {
 					echo "Invalid MAC address: $mac_addr"
 					exit 1
 				fi
+				;;
+			-d=* | --dist-key-size=*)
+				key_size="${i#*=}"
+				if [ "$(($key_size))" -gt 64 ] || [ "$(($key_size))" -lt 1 ]; then
+					echo "Invalid dist_key_size=$key_size. Valid range is [1-64]."
+					exit 1
+				fi
+				dpni_args=$dpni_args" --dist-key-size="$key_size
 				;;
 			-nq=* | --num-queues=*)
 				num_queues="${i#*=}"
