add support for num cgs in restool for mc 10.14
Signed-off-by: Hemant Agrawal <hemant.agrawal@nxp.com>
Signed-off-by: Ioana Ciornei <ioana.ciornei@nxp.com>

diff --git a/scripts/ls-main b/scripts/ls-main
--- a/scripts/ls-main
+++ b/scripts/ls-main
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Copyright 2013-2016 Freescale Semiconductor Inc.
-# Copyright 2017-2018 NXP
+# Copyright 2017-2019 NXP
 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -640,7 +640,7 @@ The options are:
 	-o, --options=OPTIONS				Comma separated options. Supported values are:
 							DPNI_OPT_TX_FRM_RELEASE, DPNI_OPT_NO_MAC_FILTER,
 							DPNI_OPT_HAS_POLICING, DPNI_OPT_SHARED_CONGESTION,
-							DPNI_OPT_HAS_KEY_MASKING, DPNI_OPT_NO_FS.
+							DPNI_OPT_HAS_KEY_MASKING, DPNI_OPT_NO_FS, DPNI_OPT_CUSTOM_CG.
 	-nq, --num-queues=NUM_QUEUES			Number of TX/RX queues use for traffic distribution.
 							Valid range [1-16]. Default value is number of cores.
 	-t, --num-tcs=NUM_TCS				Number of traffic classes (TCs) reserved for the DPNI.
@@ -654,6 +654,8 @@ The options are:
 							By default, set to 64.
 	-f, --fs-entries=FS_ENTRIES			Number of entries in the flow steering table.
 							Valid range [1-1024]. Default value is 64.
+	-g, --num-cgs=CONGESTION_GROUPS			Number of congestion groups (CGs), reserved for the DPNI.
+							Valid range [1-128]. Defaults to one per TC.
 	-c, --container <dprc.X>                        Specifies the parent container name. e.g. dprc.2, dprc.3 etc.
 
 <endpoint> is one of the following:
@@ -777,6 +779,14 @@ process_addni() {
 					exit 1
 				fi
 				dpni_args=$dpni_args" --fs-entries="$fs_entries
+				;;
+			-g=* | --num-cgs=*)
+				num_cgs="${i#*=}"
+				if [ "$(($num_cgs))" -gt 8 ] || [ "$(($num_cgs))" -lt 1 ]; then
+					echo "Invalid num_cgs=$num_cgs. Valid range is [1-128]."
+					exit 1
+				fi
+				dpni_args=$dpni_args" --num-cgs="$num_cgs
 				;;
 			-l=* | --label=*)
 				label="${i#*=}"
