update wrapper scripts to MC10.0.0 ABI
Signed-off-by: Ioana Ciornei <ioana.ciornei@nxp.com>

diff --git a/scripts/ls-main b/scripts/ls-main
--- a/scripts/ls-main
+++ b/scripts/ls-main
@@ -578,27 +578,26 @@ usage_addni() {
 	echo "Usage: $0 [OPTIONS] <endpoint>
 The options are:
 	-h, --help					This message.
-	-a, --mac-addr=XX:XX:XX:XX:XX:XX		Mac address of the network interface.
-							Default value is 00:00:00:00:00:00 allowing the
-							Ethernet driver to randomly allocate one.
-	-d, --max-dist-per-tc=MAX_DIST_PER_TC		Maximum distributions per traffic class.
-							The values are rounded up to the nearest power of 2.
-							Valid range is [1-8]. Default value is 8.
 	-l, --label=LABEL				The label of the resulting DPNI object associated to the
 							network interface. Maximum length must be 15 characters.
 	-n, --no-link					The network interface will not be linked to any endpoint
 	-o, --options=OPTIONS				Comma separated options. Supported values are:
-							DPNI_OPT_MULTICAST_FILTER, DPNI_OPT_UNICAST_FILTER,
-							DPNI_OPT_DIST_HASH, DPNI_OPT_DIST_FS
-							Default value is: DPNI_OPT_MULTICAST_FILTER,
-							DPNI_OPT_UNICAST_FILTER,DPNI_OPT_DIST_HASH,DPNI_OPT_DIST_FS
-	-s, --max-senders=NUM_SENDERS			Maximum number of senders.
-							Valid range is [1-8]. Default value is 8.
-	-t, --max-tcs=NUM_TCS				Maximum number of traffic classes.
-							Default value is 1.
-	-k, --max-dist-key-size=KEY_SIZE		Maximum key size for the distribution.
-							Also sets DPNI_OPT_FS_MASK_SUPPORT as an option.
-							Default value is 24.
+							DPNI_OPT_TX_FRM_RELEASE, DPNI_OPT_NO_MAC_FILTER,
+							DPNI_OPT_HAS_POLICING, DPNI_OPT_SHARED_CONGESTION,
+							DPNI_OPT_HAS_KEY_MASKING, DPNI_OPT_NO_FS.
+	-q, --num-queues=NUM_QUEUES			Number of TX/RX queues use for traffic distribution.
+							Valid range [1-8]. Default value is 1.
+	-t, --num-tcs=NUM_TCS				Number of traffic classes (TCs) reserved for the DPNI.
+							Valid range [1-8]. Default value is 1.
+	-m, --mac-entries=MAC_ENTRIES			Number of entries in the MAC address filtering table.
+							Valid range [1-80]. Default value is 80.
+	-v, --vlan-entries=VLAN_ENTRIES			Number of entries in the VLAN address filtering table.
+							Valid range [1-16]. By default, VLAN filtering is
+							disabled.
+	-q, --qos-entries=QOS_ENTRIES			Number of entries in the QoS classification table.
+							By default, set to 64.
+	-f, --fs-entries=FS_ENTRIES			Number of entries in the flow steering table.
+							Valid range [1-1024]. Default value is 64.
 
 <endpoint> is one of the following:
 	dpmac.X 					X is the index of the dpmac object
@@ -614,24 +613,8 @@ Usage examples:
 # Create a DPNI and its private dependencies
 create_dpni() {
 
-	# Parameter adjusting, to allow us create
-	# the real number of necessary DPCONs.
-	case $max_dist_per_tc in
-		[0-1])
-			no_of_dpcons=1
-			;;
-		2)
-			no_of_dpcons=2
-			;;
-		[3-4])
-			no_of_dpcons=4
-			;;
-		[5-8])
-			no_of_dpcons=8
-			;;
-		*)
-			return
-	esac
+	# TODO
+	no_of_dpcons=8
 
 	# Create private dependencies
 	create_dpbp
@@ -643,17 +626,16 @@ create_dpni() {
 		fi
 	done
 
-	# Restrictions: max-tcs must be 1, max-senders must be 8.
-	# Set mac addr to all-zero, allowing the Eth driver to randomly
-	# allocate one.
 	dpni=$($restool --script dpni create			\
-		--mac-addr="$mac_addr"				\
-		--max-senders="$max_senders"			\
-		--max-tcs="$max_tcs"				\
-		--max-dist-per-tc="$max_dist_per_tc"		\
+		--num-queues="$num_queues"			\
+		--num-tcs="$num_tcs"				\
+		--mac-entries="$mac_entries"			\
+		--vlan-entries="$vlan_entries"			\
+		--qos-entries="$qos_entries"			\
+		--fs-entries="$fs_entries"			\
 		--options="$options"				\
-		$max_dist_key_size_arg				\
 	)
+
 	if [ -z "$dpni" ]; then
 		echo "Error: dpni object was not created!"
 		return 1
@@ -670,12 +652,14 @@ create_dpni() {
 
 process_addni() {
 	no_link=0
-	mac_addr=00:00:00:00:00:00
-	max_dist_per_tc=8
-	max_senders=8
-	max_tcs=1
-	options=DPNI_OPT_MULTICAST_FILTER,DPNI_OPT_UNICAST_FILTER,DPNI_OPT_DIST_HASH,DPNI_OPT_DIST_FS
+	options=
 	label=
+	num_queues=0
+	num_tcs=0
+	mac_entries=0
+	vlan_entries=0
+	qos_entries=0
+	fs_entries=0
 
 	#Endpoint object provided as argument
 	endpoint=
@@ -690,18 +674,45 @@ process_addni() {
 				usage_addni
 				exit 1
 				;;
-			-a=* | --mac-addr=*)
-				mac_addr="${i#*=}"
-
-				if [[ ! "$mac_addr" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]]; then
-					echo "Invalid MAC address: $mac_addr"
+			-q=* | --num-queues=*)
+				num_queues="${i#*=}"
+				if [ "$num_queues" -gt 8]; then
+					echo "Invalid num_queues=$num_queues. Valid range is [1-8]."
 					exit 1
 				fi
 				;;
-			-d=* | --max-dist-per-tc=*)
-				max_dist_per_tc="${i#*=}"
-				if [ "$max_dist_per_tc" -gt 8 ]; then
-					echo "Invalid max_dist_per_tc=${max_dist_per_tc}. Valid range is [1-8]."
+			-t=* | --num-tcs=*)
+				num_tcs="${i#*=}"
+				if [ "$num_tcs" -gt 8]; then
+					echo "Invalid num_tcs=$num_queues. Valid range is [1-8]."
+					exit 1
+				fi
+				;;
+			-m=* | --mac-entries=*)
+				mac_entries="${i#*=}"
+				if [ "$mac_entries" -gt 80]; then
+					echo "Invalid mac_entries=$mac_entries. Valid range is [1-80]."
+					exit 1
+				fi
+				;;
+			-v=* | --vlan-entries=*)
+				vlan_entries="${i#*=}"
+				if [ "$vlan_entries" -gt 16]; then
+					echo "Invalid vlan_entries=$vlan_entries. Valid range is [1-16]."
+					exit 1
+				fi
+				;;
+			-q=* | --qos-entries=*)
+				qos_entries="${i#*=}"
+				if [ "$qos_entries" -gt 64]; then
+					echo "Invalid qos_entries=$qos_entries. Valid range is [1-64]."
+					exit 1
+				fi
+				;;
+			-f=* | --fs-entries=*)
+				fs_entries="${i#*=}"
+				if [ "$fs_entries" -gt 1024]; then
+					echo "Invalid fs_entries=$fs_entries. Valid range is [1-1024]."
 					exit 1
 				fi
 				;;
@@ -717,16 +728,6 @@ process_addni() {
 				;;
 			-o=* | --options=*)
 				options="${i#*=}"
-				;;
-			-s=* | --max-senders=*)
-				max_senders="${i#*=}"
-				;;
-			-t=* | --max-tcs=*)
-				max_tcs="${i#*=}"
-				;;
-			-k=* | --max-dist-key-size=*)
-				max_dist_key_size="${i#*=}"
-				options="$options,DPNI_OPT_FS_MASK_SUPPORT"
 				;;
 			*(dprc.+([0-9])/)dpmac.+([0-9]))
 				no_link=0
@@ -750,9 +751,6 @@ process_addni() {
 				;;
 		esac
 	done
-
-	# create optional --max-dist-key-size argument
-	[ ! -z "$max_dist_key_size" ] &&  max_dist_key_size_arg="--max-dist-key-size=$max_dist_key_size"
 
 	# Check if --no-link the endpoint have been provided otherwise display the usage
 	if [ $no_link -eq 0 ] && [ -z "$endpoint" ]; then
